// ============================================================
// OpenClaw Deploy — Autonomous Task Types
// ============================================================

import type { GeneratedFile } from '../../../types/index.js';

/** Lifecycle states for an autonomous task. */
export type TaskStatus =
  | 'pending'
  | 'planning'
  | 'executing'
  | 'paused'
  | 'completed'
  | 'failed'
  | 'cancelled'
  | 'budget_exceeded';

/** Safety classification for tool operations during autonomous execution. */
export type SafetyTier = 'safe' | 'moderate' | 'sensitive' | 'dangerous';

export interface ResourceBudget {
  maxTokens: number;
  maxApiCalls: number;
  maxToolCalls: number;
  maxDurationMs: number;
  maxSubtasks: number;
  tokensUsed: number;
  apiCallsUsed: number;
  toolCallsUsed: number;
  startedAt: number;
}

export interface Subtask {
  id: string;
  parentTaskId: string;
  index: number;
  description: string;
  prompt: string;
  safetyTier: SafetyTier;
  status: TaskStatus;
  result?: string;
  error?: string;
  toolsUsed: string[];
  tokensUsed: number;
  startedAt?: string;
  completedAt?: string;
  /** Nesting depth: 0 = top-level subtask, 1 = child of a subtask, etc. */
  depth: number;
  /** Child subtasks spawned by decomposition (if any) */
  children?: Subtask[];
  /** Indices of subtasks this one depends on (must complete first) */
  dependsOn?: number[];
  /** Key to write this subtask's result into shared agent state */
  outputKey?: string;
  /** Agent profile ID for specialist execution (e.g., 'researcher', 'coder') */
  agentProfile?: string;
  /** Files generated by this subtask (PDFs, presentations, etc.) */
  generatedFiles?: GeneratedFile[];
}

export interface AutonomousTask {
  id: string;
  goal: string;
  userId: string;
  chatId: number | string;
  channel: 'telegram' | 'webchat' | 'discord';
  status: TaskStatus;
  subtasks: Subtask[];
  plan?: string;
  budget: ResourceBudget;
  auditLog: AuditEntry[];
  createdAt: string;
  updatedAt: string;
  completedAt?: string;
  finalSummary?: string;
}

export type AuditEvent =
  | 'task_created'
  | 'planning_started'
  | 'planning_completed'
  | 'subtask_started'
  | 'subtask_completed'
  | 'subtask_failed'
  | 'tool_executed'
  | 'approval_requested'
  | 'approval_granted'
  | 'approval_denied'
  | 'approval_timeout'
  | 'budget_warning'
  | 'budget_exceeded'
  | 'task_paused'
  | 'task_resumed'
  | 'task_completed'
  | 'task_failed'
  | 'task_cancelled'
  | 'kill_switch_activated'
  | 'circuit_breaker_tripped'
  | 'error';

export interface AuditEntry {
  timestamp: string;
  event: AuditEvent;
  details: string;
  subtaskId?: string;
  toolName?: string;
  safetyTier?: SafetyTier;
  approved?: boolean;
  tokensUsed?: number;
}

export interface AutonomousConfig {
  enabled: boolean;
  defaultBudget: {
    maxTokens: number;
    maxApiCalls: number;
    maxToolCalls: number;
    maxDurationMs: number;
    maxSubtasks: number;
  };
  safetyTierOverrides?: Record<string, string>;
  autoApproveModerate: boolean;
  maxConcurrentTasks: number;
  progressIntervalMs: number;
  planningModel: 'anthropic';
  /** Max sub-agent nesting depth. 0 = no nesting, 1 = subtasks can spawn children, etc. Default: 1 */
  maxSpawnDepth: number;
  /** Optional Discord channel ID to post completion/failure reports to */
  reportChannelId?: string;
}
